### ISSUE TITLE
Proposal: Snowflake proxy deployment

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#124]
I propose we run a snowflake proxy on our netcup servers: https://snowflake.torproject.org/

Putting it brief, Snowflake is a bridge that allows people from censored countries to connect to Tor using Snowflake as a forwarder. There are also browser extensions for it: https://snowflake.torproject.org/ and https://chrome.google.com/webstore/detail/snowflake/mafpmfcccpbjnhfhjnllmmalhifmlcie. Since we only forward encrypted content and bridge IP addresses are private, there is no potential for problems (like with exit relays). Deploying this would allow people living in countries with heavily censored internet to circumvent firewalls blocking Tor relays and allow them to access the open internet.

There is a [Debian package](https://packages.debian.org/bookworm/snowflake-proxy) for it and setup would basically consist of installing the package and starting the service. Then in terms of resource usage, only bandwidth is really relevant.

Would be happy to hear the team's thoughts on this.

**Comment by ChrisLovering** [comment]
SGTM

**Comment by ChrisLovering** [comment]
After discussing with Admins we've come to the conclusion that since netcup gave us these servers as a sponsorship for our infra, running something that isn't our infra seemed wrong.

So while we think it's an important service, it doesn't seem appropriate to run it on this infra.
