### ISSUE TITLE
Adding a mermaid service

### ISSUE THREAD

**Issue by shtlrs** [python-discord/infra#139]
I was wondering whether it would be a good idea to have a mermaid service that our bots can prompt within the cluster. (Or even expose it publicy)

This would enable people that might have an idea to illustrate it better through a diagram.

This will be made as a bot command that would then send query the service with the mermaid diagram as input, and the bot would then dump the generated diagram as an image in the thread/channel.

I have found this [repo](https://github.com/TomWright/mermaid-server) which already has the image ready for pulling and usage.

If this ever gets approved, I'd like to work on and deploy it myself.

**Comment by jb3** [comment]
I disagree here and think that for the layman and average Discord user Mermaid is considerably more powerful with the same effort levels. The solution to doing something like a sequence diagram in GraphViz is to look on StackOverflow, where it then tells you to use UML software. With Mermaid?

```mermaid
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
```

With reasonable resource limiting, maybe harnessing the netcup machines, and reasonable limitations on how much compute a single user can use I think the downside of having to run a headless browser is considerably outweighed by the power of Mermaid, as well as it's now native integration into platforms like GitHub.

![image](https://github.com/python-discord/infra/assets/20439493/bff0a8d3-78f9-430e-a3cf-1cc4c046d24f)

With more types of diagram than fingers I have on both my hands I think this is an incredibly powerful tool that our users would benefit from, the documentation is much more beginner friendly than the GraphViz documentation, the outputted diagrams are pretty without needing a load of non-default configuration, and I think overall given the adoption of Mermaid by other major platforms it would not go amiss to have some sort of in-Discord integration of this tool.

**Comment by shtlrs** [comment]
We've agree that this isn't something worth doing after all as it's easier to do all available web apps than host it ourselves.
