### ISSUE TITLE
Investigate dependabot pull request grouping

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#142]
Dependabot now allows you to group together multiple
  dependency updates into a single pull request.

Possible approaches suggested: Group all the docker updates together, group
    any linting dependencies together (would just require a big RegEx).
    Dependabot natively works with its own dependency groups here (e.g. Docker,
    Pip).

**Comment by jb3** [comment]
I believe for a good amount of repos we have made this grouping now?

Generally, I find it easier to do the following:
- If we have a single dependency update and it passes, we can merge it.
- If we have multiple dependency updates, or a dependency update that is failing, then clone the repo and push one PR to do the update manually. Dependabot is smart enough to pretty swiftly bulk close the PRs when it realises that the information is out of date.

**Comment by jchristgit** [comment]
Yeah, we probably don't need to do anything here anymore.
