### ISSUE TITLE
Install and configure Podman on all hosts

### ISSUE THREAD

**Issue by jb3** [python-discord/infra#18]
- [x] Install Podman on all hosts
- [ ] Configure Podman to assign pods IPs on the Wireguard subnet allocated to each host
- [ ] Configure Podman services to use host cgroup and run managed by systemd
- [ ] Setup monitoring for Podman
- [ ] Talk more about how we want DNS to work

**Comment by jb3** [comment]
Great work @jchristgit!

**Comment by jchristgit** [comment]
Regarding "Configure Podman services to use host cgroup and run managed by systemd":

```
[Unit]
Description = Gobble the memory

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Type = forking

PIDFile=%t/%n-pid
RuntimeDirectory= %n
ExecStartPre = /bin/rm -f %t/%n-pid %t/%n-cid
ExecStart = /usr/bin/podman run \
  --cgroups=no-conmon \
  --cgroups=disabled \
  --log-driver=journald \
  --cidfile %t/%n-cid \
  --conmon-pidfile %t/%n-pid \
  --detach \
  --name gobbler \
  gobbler 
ExecStop = /usr/bin/podman stop --ignore --cidfile %t/%n-cid
ExecStopPost = /usr/bin/podman rm --ignore -f --cidfile %t/%n-cid
MemoryMax = 300M
MemoryLimit = 300M
```

**Comment by jchristgit** [comment]
@jb3 I still don't get the podman IP part, but can you take care of it, or maybe we can set up a call and figure out how that's done?

**Comment by jchristgit** [comment]
I am thrilled to announce that we have solved the issue of having to configure
a container engine on our hosts ourselves by deciding to configure a container
cluster management orchestration solution instead.
