### ISSUE TITLE
"Status Embed" workflow always fails

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#214]
The [status embed
workflows](https://github.com/python-discord/infra/actions/workflows/status_embed.yaml)
either fail or are skipped. It seems the last success was two weeks ago, before
that a month ago, and then four months ago.

Calling the endpoint manually via `curl` looks fine. Are we maybe hitting a
ratelimit? We should either fix the workflow, allow failure - so no
notifications are dispersed - or remove it.

**Comment by shtlrs** [comment]
@jchristgit we ran into this issue before and i fixed it on the other repos by replacing the wget call with curl.

I couldn't be exactly certain of why, but I remeber the theory of it related to wget's user agent.

Didn't spend much time on debugging as it worked just fine with curl and the first request we make is with curl so voilà.

**Comment by jchristgit** [comment]
Hmm, we are already using curl though.

I have an idea. I'm going to tee the output of the curl request to see
what comes out of it. Maybe we can see something there.

**Comment by shtlrs** [comment]
@jchristgit We're using both.
https://github.com/python-discord/infra/blob/546fa6555d0cba300486f035ae8ca7fecc30d345/.github/workflows/status_embed.yaml#L39

That's the line that has caused the issues before, and that's the one that I think should be replaced.

**Comment by jchristgit** [comment]
Ahh, apparently I'm blind.

For some strange reason the pipeline with the `tee` recently worked. But
then the debugging step is obsolete either way. Do you want to update
this to `curl`? Should I?

**Comment by jchristgit** [comment]
I think there's also the slight possibility that `$DOWNLOAD_URL` being
unquoted might cause issues. But we will see either way.
