### ISSUE TITLE
Bootstrap systems using Ansible

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#216]
At the moment we utilize [our bootstrap
script](https://github.com/python-discord/infra/blob/main/server_bootstrap.sh)
to initialize new servers.

It would be preferable to have all our server configuration centralized in
Ansible: with the new server setup tasks in the Ansible roles including user
configuration, we should evaluate whether we can make servers run
[`ansible-pull`](https://docs.ansible.com/ansible/latest/cli/ansible-pull.html)
on the repository to perform the initial setup, and adjust the bootstrap script
accordingly.

**Comment by shtlrs** [comment]
Is the idea here to use the `ansible.posix.authorized_key` module to add the different keys by having it from the pydis users vars ?

**Comment by jchristgit** [comment]
That would be part of it - we do that as part of the `pydis-users` role and I think maybe we should have a separate playbook that just has these "setup" tasks, for now I think that would be `pydis-users` and `common`

**Comment by jchristgit** [comment]
Not sure if `ansible-pull` will work as we expect it to.

I think we should:

- add a new `bootstrap.yml` playbook
- change the server setup script to do this:
  ```sh
  apt-get install -y ansible-core git
  pushd $(mktemp -d)
  git clone --depth 1 https://github.com/python-discord/infra
  cd infra/ansible
  ansible-galaxy install -r roles/requirements.yml
  ansible-playbook bootstrap.yml
  ```

Bonus point if we can somehow make it parse its own inventory information out
(we will need to tell it to deploy on localhost, which may need a separate
inventory, but I mean if we add a new host and it can automatically figure out
who it is).

**Comment by shtlrs** [comment]
Closed as per request of the owner.
