### ISSUE TITLE
Set up prometheus-blackbox-exporter in Ansible

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#218]
Add a new role, named `prometheus-blackbox-exporter` (the
`prometheus-node-exporter` role can be taken as a guideline), and adjust our
playbook to install it on lovelace as part of the monitoring play.

Next up, adjust the Prometheus configuration (found in the Prometheus role
defaults) to scrape the blackbox exporter.

The `prometheus-blackbox-exporter` role should also allow configuration of the
blackbox exporter. For this, copy the configuration file from the current
distribution default, place it in the `templates` directory of the role, and
`template:` it over as part of the role. The exporter should be restarted on
changes. We might want to customize this such that an SSH access check can be
used.

**Comment by shtlrs** [comment]
I'll have a stab at this myself.

**Comment by shtlrs** [comment]
I was wondering, what default config would we have for prometheus here ?

which services will blackbox be probing by default ? Since those need to be included in prometheus in order for prometheus to relabel them properly

**Comment by jchristgit** [comment]
As a "getting started" thing I think we should just probe SSH on turing
and lovelace. That seems like something important enough to monitor that
we can start out with.
