### ISSUE TITLE
Evaluate deploying Apache Superset instead of Metabase

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#225]
At the moment we use Metabase for our statistics.

This uses custom user accounts that are manually created, and it's not written
in Python. [Apache Superset](https://superset.apache.org/) is completely open
source (Metabase is a company), is written in Python, and supports custom
authentication such as with GitHub.

I believe as part of the PostgreSQL migration to Netcup we should deploy
Superset on the Netcup nodes and see if it could be a viable replacement.
Obviously, all current functionality used by our team should work the same way,
but perhaps we could even use Superset for more, such as integrating what
currently powers https://stats.pythondiscord.com into it and / or allowing
members to query our public data (under constrained resources).

**Comment by jb3** [comment]
After discussion, we don't need to consider this move for now. After migrating
PostgreSQL to Netcup we are much better on resources and no longer need to make
this change.

Metabase for now handles the needs of Administrators and the integrations with
python-discord/bot are solid.
