### ISSUE TITLE
Connect Prometheus alerts on netcup to Kubernetes Alertmanager

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#240]
We want to be able to configure alerts on the Netcup Prometheus instance and
act on it accordingly, with the alerting configuration and HA alertmanager
setup running in Kubernetes.

Joe might be able to give us a token that we can use to talk to Alertmanager in
Kubernetes, and connect our Prometheus instance to it.

**Comment by jchristgit** [comment]
@jb3 assigning you since you probably know how to quickly add access to the AM instance

**Comment by jb3** [comment]
Netcup nodes now have an IP bypass to be able to hit AlertManager, they can hit the AlertManager service at https://alertmanager.pythondiscord.com/
