### ISSUE TITLE
Create operations link overview at ops.pydis.wtf

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#242]
To ease finding any resources we use for operations, we could configure a
simple HTML page with links to all ops-related websites. A listing can be found
at #230.

To do this, we should write an Ansible role that configures a new nginx virtual
host on HTTP, reload nginx, fetch certificates using this host, then configure
the new HTTPS vhost with a webroot such as `/var/www/ops.pydis.wtf` and in
there place an `index.html` that is a (slightly styled) listing of ops-related
resources.

**Comment by jchristgit** [comment]
I have a nginx role that does the heavy lifting using certbot and a config file
that properly configures the nginx webroot which I believe we should use here.
I will open source this tomorrow and post an update here.

**Comment by jchristgit** [comment]
As discussed with Joe, this could also just be a GitHub Pages setup.

**Comment by jchristgit** [comment]
Role has been open sourced: https://github.com/jchristgit/ansible-role-nginx-letsencrypt

**Comment by jb3** [comment]
I have deployed something at [ops.pydis.wtf](https://ops.pydis.wtf/) now.

It is overkill, I know, but:
- I am happy to maintain this (though adding services is literally [editing a YAML file](https://github.com/python-discord/ops-site/blob/main/data/services.yaml) and it auto-deploys, anyone can do that)
- It runs without JavaScript enabled and is a static site, it just uses JavaScript for the site-generation and optionally for service filtering on the built site.
- It is a simple enough service that the bus factor is low, if it becomes unmaintainable in the future:
  a) It won't break, once the HTML is generated, it's generated.
  b) It's a simple enough & non-critical-path service that it can be stripped and replaced down the line with minor effort and no consequence

**Comment by jchristgit** [comment]
> It runs without JavaScript enabled and is a static site, it just uses JavaScript for the site-generation and optionally for service filtering on the built site.

>  a) It won't break, once the HTML is generated, it's generated.

Very very good. Thanks man
