### ISSUE TITLE
h deployment

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#26]
Our most important backing service, this needs to be set up as soon as possible due to the sheer amount of usefulness encapsulated in such a great deployment service.

This may be a good task to jump into the deployment setup with Ansible, and once we have the previous issues done, we can admit somebody to the DevOps team to take care of it.

**Comment by imsofi** [comment]
I will give my sincerest comment on this issue, for Cleiner.

**Comment by jchristgit** [comment]
- Template a systemd service to run podman
  - No registry authentication is needed
  - Resource limits would be great
- Template NGINX configuration
  - Help from @jb3 and @jchristgit for questions 
  - Reload nginx on change

For the nginx deployment, see https://github.com/python-discord/infra/tree/main/roles/nginx-cloudflare-mtls for the mutual TLS configuration. @jb3 knows more on this topic.
