### ISSUE TITLE
Plan data migration for site

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#265]
Once all backing PostgreSQL infrastructure has been set up, we want to migrate
the database and data for the site.

This issue will be used as a tracker to plan it and create separate issues that
don't relate to the PostgreSQL setup itself but are concerned with migrating
the data safely and with as little downtime as possible.

From the top of my head, we need to:

- Update connection strings in site and metabase
- Shut them down for maintenance
- Dump and restore data in the lovelace database

**Comment by jb3** [comment]
This has now been completed with the migration of data from Kubernetes Postgres
to Ansible Postgres.
