### ISSUE TITLE
Bitwarden deployment

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#27]
Needs PostgreSQL and data migration.

> "We actually need to configure it properly and put SMTP information in the environment variables instead of just putting it everywhere"
>
> - Joe Banks, DevOps Engineer

**Comment by jchristgit** [comment]
@imsofi @jb3 please tell me your availability here, let's do a call where we work through this

**Comment by imsofi** [comment]
Im usually available after 18:00 CEST in the weekdays. Weekends are often very hit or miss. So Wednesday to Friday after 18:00 this week would work fine for me.

**Comment by jchristgit** [comment]
@jb3 we need your help here

**Comment by jchristgit** [comment]
@ChrisLovering Any news here?
