### ISSUE TITLE
Redis deployment

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#29]
The Voices want to use KeyDB here instead, but their arguments come from weak minds.

> "We're using KeyDB" - Voice 1

**Comment by jchristgit** [comment]
Voice 2 wants to mention that Chris is Voice 1.

**Comment by jb3** [comment]
We're using KeyDB.

**Comment by jb3** [comment]
Thanks.

**Comment by jchristgit** [comment]
@jb3, KeyDB has virtually no benefits for Python Discord, apart from complicating the deployment.
