### ISSUE TITLE
Prometheus access via SSH port forwarding

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#325]
Our Prometheus mTLS deployment is making it impossible to access the Prometheus server directly over SSH port forwarding.

Joe said he is on it.

**Comment by jb3** [comment]
I think with the distribution of nTLS keys and the ease to deploy them into browsers this is rectified.

Any modern browser will support this and completely removes the need for any sort of forwarding whilst maintaining cryptographically secure authentication.

Please close if you are satisfied, else I will find another solution. I'm open to either :shipit:
