### ISSUE TITLE
Snekbox deployment

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#35]
Mr. Hemlock does not have the time for this right now, because it's the middle of Texas season.

Mark might be interested in doing this.

**Comment by jchristgit** [comment]
Hi @MarkKoz, do you want to sit together with us and work on this?

**Comment by MarkKoz** [comment]
Yes, but I will likely be learning more than doing due to lack of experience. We'll just need to figure out a good time to work on it.
