### ISSUE TITLE
Retiring turing

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#395]
As discussed in the DevOps meeting, we should get rid of turing.

    The reason is that it's not really used anymore, outside of a simple webserver.

    - [x] Move the webserver to lovelace
    - [x] Remove turing from the inventory
    - [x] Remove turing from monitoring
    - [x] Remove turing from our documentation
    - [ ] Power turing down
    - [ ] Return the server to Netcup

**Comment by jb3** [comment]
> @jb3 Any updates here? Can we return the server?

I think this might be something @ChrisLovering might need to do? I'm unsure.

**Comment by ChrisLovering** [comment]
Request for decommission sent to netcup.
