### ISSUE TITLE
New RRDTool-based statistics infrastructure

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#396]
As discussed in the team meeting, we want to set up a new RRDtool-based long term statistics infrastructure.

Currently this is a bunch of cron jobs on my lovelace crontab. We want to ansibl-ize this into a proper system service.

The first step here is to 1. set up the rrdtool PostgreSQL user, and 2. gather
the statistics my script is currently gathering. We can then go from there.

**Comment by jb3** [comment]
What is the status of this now the PR is merged? Are we able to see these stats anywhere?
