### ISSUE TITLE
Document local linting workflow

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#422]
Currently, when a pipeline fails, all ``pre-commit`` tells us is that "files were modified by this hook". See for example:

- https://github.com/python-discord/infra/actions/runs/10082093596/job/27875579374?pr=421
- https://github.com/python-discord/infra/actions/runs/10082218337/job/27875973714?pr=403

It would be nice if it could actually say _which_ files are being changed, and
perhaps even propose a diff, or perhaps even fix it for me.

**Comment by jb3** [comment]
I do believe the solution here is just using pre-commit. I am not necessarily saying use it as a Git hook as I know that does not work with everyones workflow, however, we have a task defined explicitly for this:

```
poetry run task lint
```

We already have pre-commit as a dependency, we already have this environment installed locally to have people work on Ansible.

![image](https://github.com/user-attachments/assets/24f7be0d-ce48-4212-8cf0-73dbaa786b7a)

We could certainly document this better and see if there are options to make pre-commit more verbosely identify what the issues are in CI, but the ultimate solution to this is to use the lint step locally, which will (as you suggest) make those changes for you.
