### ISSUE TITLE
Possible duplicate labels for GitHub actions

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#423]
We currently have two labels for what's presumably issues and pull requests related to GitHub Actions:

- `github_actions`, kind of a lone wolf that doesn't match our naming scheme, and
- `group: github actions`, which matches our regular naming scheme.

Can we get rid of `github_actions` or is it something automatically made by GitHub?

**Comment by jb3** [comment]
`github_actions` was used by dependabot to label GitHub Actions version updates. I have removed it now, `group: github actions` is the relevant label.
