### ISSUE TITLE
Restrict saslauthd user

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#478]
`saslauthd` currently runs as root. This is bad.

`man saslauthd` documents that:

>    saslauthd should be started from the system boot scripts when going to multi-user mode. When run‐
>    ning against a protected authentication database (e.g. the shadow mechanism), it must be run as
>    the superuser. Otherwise it is recommended to run daemon unprivileged as saslauth:saslauth, re‐
>    quiring the runtime directory to have root:saslauthd owner. You can do so by following these steps
>    in machines using systemd(1) :

>    1.   create directory /etc/systemd/system/saslauthd.service.d/
>    2.   create file /etc/systemd/system/saslauthd.service.d/user.conf with content
>
>         [Service]
>         User=saslauth
>         Group=saslauth
>
>    3.   Reload systemd service file: run “systemctl daemon-reload”

After discussion with Joe, we do not use `saslauthd` for shadow auth.

We should therefore implement this to improve system security.

**Comment by MarkKoz** [comment]
Hi, thanks for writing this up! I'd like to work on this. It looks within my means and like a good opportunity to get my feet wet again with infrastructure work 😁.

**Comment by jb3** [comment]
Assigned, there is already a SASL role that should help here.

Another thing to note is that following #480 we no longer need SASL for Postfix (Dovecot handles this), so whilst setting this up moving SASLauthd back to the default socket location (from the /var/spool/postfix one, it should be easy to grep for), would be a good security measure.

**Comment by MarkKoz** [comment]
How do we test changes? Is there a testing/staging environment available for use?

**Comment by jb3** [comment]
There is a local testing project that Bella has set up, in the Ansible directory, though I don't know how effective it is at testing mail-server or SASL related changes due to the dependency on moving components outside the scope of Ansible.

**Comment by MarkKoz** [comment]
Nice, cheers to Bella for setting that up. I'll try it out. I can gain some confidence if I can at least see the service running under the correct user/group, and there aren't permission issues reading the config files.

**Comment by MarkKoz** [comment]
Okay, this looks like it's gonna more involved. I typically use a VM to run Linux, and it's not able to run VirtualBox within. I think I'll have to switch to WSL.

**Comment by shtlrs** [comment]
> Okay, this looks like it's gonna more involved. I typically use a VM to run Linux, and it's not able to run VirtualBox within. I think I'll have to switch to WSL.

@MarkKoz  Which issues are you running into. precisely ?

**Comment by MarkKoz** [comment]
I use VMWare to run Linux on Windows. I got the following error from Vagrant:

> VBoxManage: error: AMD-V is not available (VERR_SVM_NO_SVM)

VMWare has a "Virtualize Intel VT-x/EPT or AMD-V/RVI" setting. However, VMWare tells me it's not supported on my system when I try to use it. Apparently that can be caused by having HyperV enabled on Windows, which I want to have enabled for podman and WSL to work. It may also be caused by having Virtualization-based Security enabled on Windows, and that doesn't sound like something I want to keep disabled.
