### ISSUE TITLE
Deciding on documentation space

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#49]
We need a central space for documenting topics of this deployment.

I would be happy to hear the team's thoughts here - what's a good, approachable place to put this?

**Comment by jchristgit** [comment]
cc @jchristgit @ChrisLovering @MrHemlock @minalike what would be the most approachable spot to find documentation?

**Comment by jchristgit** [comment]
Let's use markdown for this, especially with the new flowchart support.

**Comment by jchristgit** [comment]
@jb3 will set this up, link and structure it accordingly.

**Comment by MarkKoz** [comment]
The first thing that comes to mind is Notion. The next thing that comes to mind is static page using GH Pages (never attempted this, so I don't know how involved it is). Lastly, it could just be loose files in a directory on this repo, but that's more difficult to navigate.

**Comment by jchristgit** [comment]
Hi @jb3! Any updates on this issue?

**Comment by jchristgit** [comment]
> if you've got solution ideas i'm happy to have people present and we collectively decide - i just don't have a load of time right now to source those ideas myself and consider all options proportionately

**Comment by jchristgit** [comment]
@ChrisLovering @imsofi would be happy to also have your input here!

The new suggestion: markdown documentation built and published using GitHub pages living in the Git repository

**Comment by ChrisLovering** [comment]
Getting some markdown together will be a good start, we can push that to github pages some point after that if needed.

**Comment by ChrisLovering** [comment]
Duplicate of https://github.com/python-discord/infra/issues/113
