### ISSUE TITLE
cgit does not show indents properly

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#515]
When reviewing diffs in cgit, such as [this
one](https://git.pydis.wtf/jc/poetry-restrict-plugin/commit/?id=b36c9d63c494aceb79dec19bac572f6e3c2a5a97),
cgit fails to show the indent of files. Could this perhaps be caused by the
syntax highlighting configuration?

**Comment by jb3** [comment]
We don't do any syntax highlighting on diffs.

**Comment by jb3** [comment]
Disabled syntax highlighting to double check, but the issue remains.

There's a chance this is something along the way stripping leading whitespace. I will check Cloudflare preferences.

**Comment by jb3** [comment]
This was Cloudflare, resolved now by removing HTML minification.
