### ISSUE TITLE
ansible-lint creates tons of pointless output

### ISSUE THREAD

**Issue by jchristgit** [python-discord/infra#525]
Recent CI failure: https://github.com/python-discord/infra/actions/runs/10654685915/job/29531321784?pr=524

The ansible-lint job output contains ~500 lines of output, most of which are,
for whatever reason, Prometheus configuration files. Presumably its "jinja2
spacing could be improved" warning stems from somewhere in there, but as
somebody who just wants to figure out why CI failed, this is bordering on
absolutely useless, especially because I didn't change it.

Whilst in an ideal world we would not use `ansible-lint` to begin with, I
recognize that Joe's deep ties with Red Hat make this utopia impossible. I
understand that the tool sometimes manages to produce output that is of value
(please see "Infinite Monkey Theorem" on Wikipedia for more information), yet
the amount of time I spend troubleshooting it on a regular basis makes the
little gain I get from it pale in comparison.

Please change CI such that warnings are not reported anymore, unless (if
possible) they are part of code that was changed.

**Comment by jb3** [comment]
Yeah I'm not sure what causes this output.
    
The local setup of ansible-lint I have works, though it does complain that some
of our task names should not start with a lower-case letter, which we should
change for consistency.

On the whole, it is undeniable that `ansible-lint` *is* useful for us, the
warnings on missing file modes, task naming and variable naming *is* good to
keep us consistent, and importantly, secure, but I do agree that the noise
generated and often the invalid lint warnings do test that effectiveness at
times.

I will look into the noise generated in the log output.

**However**, as a temporary solution, we do output GitHub compatible annotations
from Ansible Lint meaning that any failing linter rules are displayed on the job
homepage: https://github.com/python-discord/infra/actions/runs/10654685915

I know this doesn't entirely help surface for those who wish to read through the
ansible-lint logs though so I'll look into this.

**Comment by jb3** [comment]
Okay so it seems the Jinja2 recommendation is just a really badly written rule
where the linter decides it also wants to play the role of formatter and outputs
it's change recommendations in the lint failure.

Brilliant.

**Comment by jb3** [comment]
I've disabled the rule in #526 now.

Output is down to nothing if no lint failures, every line generated will be
relevant to the changes proposed:

```bash
Passed: 0 failure(s), 0 warning(s) on 214 files. Last profile that met the validation criteria was 'production'.
```

I've also set up steps in the CI job to install the dependencies from the
Ansible Galaxy requirements file (with caching) to drop all the warnings about
being unable to perform options validation.
