### ISSUE TITLE
Making diagrams via GitHub's Mermaid renderer

### ISSUE THREAD

**Issue by Xithrius** [python-discord/infra#59]
With [this](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) blog post, the ability to create diagrams has been acquired.

Diagrams to provide users with information how services are connected would be quite useful for early contributors.

@jchristgit approved ~~or something~~.

**Comment by ChrisLovering** [comment]
Duplicate of #49?

**Comment by Xithrius** [comment]
I saw too late, unfortunate.
